In [3]:
import numpy as np
import os.path as op

In [3]:
adult_path = op.join('../', 'MEG', 'adult_morphed_averaged', 'numpy_saved')
child_path = op.join('../', 'MEG', 'child_morphed_averaged', 'numpy_saved')

In [7]:
adult_run2 = np.load(op.join(adult_path, 'peak_idx_adult_run2.npy'))
adult_run2

array([127, 153,  74, 141])

In [ ]:
early = yellow
late = green

child = blue
adult = red

In [9]:
X = np.array([[1, 82, 26],
             [1, 45, 49],
             [1, 71, 76],
             [1, 22, 37],
             [1, 29, 40],
             [1, 9, 0],
             [1, 12, 2],
             [1, 18, 10],
             [1, 24, 92]])

y = np.array([71, 54, 43, 45, 21, 11, 30, 45, 10]).T

B = np.linalg.inv(X.T @ X) @ X.T @ y
B

array([23.26607673,  0.68146063, -0.27713978])

In [14]:
y_hat = X @ B
y_hat

array([71.94021391, 40.35195584, 50.58715814, 28.00403875, 31.94284381,
       29.39922238, 30.8893247 , 32.76097024, 14.12427224])

In [15]:
resid = y - y_hat
resid

array([ -0.94021391,  13.64804416,  -7.58715814,  16.99596125,
       -10.94284381, -18.39922238,  -0.8893247 ,  12.23902976,
        -4.12427224])

In [24]:
RSS = np.sum(resid**2) / (len(y) - X.shape[1])
RSS

193.24206049918982

In [25]:
var_covar = RSS * np.linalg.inv(X.T @ X)
var_covar

array([[ 7.57469276e+01, -9.62256996e-01, -5.67036460e-01],
       [-9.62256996e-01,  4.21222946e-02, -1.34995270e-02],
       [-5.67036460e-01, -1.34995270e-02,  2.80577728e-02]])

In [28]:
sd_b2 = np.sqrt(var_covar[2][2])
sd_b2

0.16750454549375962